/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.project;

import java.util.Date;
import java.sql.*;
import java.text.ParseException;
import java.time.LocalDate;

import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Stiliyan
 */
public class StokaFrame extends javax.swing.JFrame {

    private String name;
    private double price;
  //  private LocalDate dateOfExpire;
    private int count;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

 //   public LocalDate getDateOfExpire() {
 //       return dateOfExpire;
 //   }

  //  public void setDateOfExpire(LocalDate dateOfExpire) {
 //       this.dateOfExpire = dateOfExpire;
  //  }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }
    
    
    public StokaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNamePrdctInsert = new javax.swing.JTextField();
        txtPricePrdctInsert = new javax.swing.JTextField();
        txtCountPrdctInsert = new javax.swing.JTextField();
        btnPrdctInsert = new javax.swing.JButton();
        txtNamePrdctDelete = new javax.swing.JTextField();
        btnPrdctDelete = new javax.swing.JButton();
        lblOutputProducts = new javax.swing.JLabel();
        btnClearPrdctFields = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaShowProducts = new javax.swing.JTextArea();
        btnShowPrdcts = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Стоки");

        txtNamePrdctInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamePrdctInsertActionPerformed(evt);
            }
        });

        txtPricePrdctInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPricePrdctInsertActionPerformed(evt);
            }
        });

        btnPrdctInsert.setText("Въведи стока");
        btnPrdctInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrdctInsertActionPerformed(evt);
            }
        });

        txtNamePrdctDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamePrdctDeleteActionPerformed(evt);
            }
        });

        btnPrdctDelete.setText("Премахни стока");
        btnPrdctDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrdctDeleteActionPerformed(evt);
            }
        });

        lblOutputProducts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnClearPrdctFields.setText("Изчисти полетата");
        btnClearPrdctFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPrdctFieldsActionPerformed(evt);
            }
        });

        btnExit.setText("Изход");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnBack.setText("Назад");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        areaShowProducts.setColumns(20);
        areaShowProducts.setRows(5);
        jScrollPane1.setViewportView(areaShowProducts);

        btnShowPrdcts.setText("Покажи всички продукти");
        btnShowPrdcts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPrdctsActionPerformed(evt);
            }
        });

        jLabel2.setText("Име");

        jLabel4.setText("Цена");

        jLabel5.setText("Бройка");

        jLabel6.setText("Име на продукт за премахване");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNamePrdctInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnPrdctInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(txtCountPrdctInsert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                                                .addComponent(txtPricePrdctInsert, javax.swing.GroupLayout.Alignment.LEADING))
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jLabel6)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnShowPrdcts, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnClearPrdctFields, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtNamePrdctDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(btnPrdctDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(39, 39, 39)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOutputProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 34, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNamePrdctInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPrdctInsert))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPricePrdctInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClearPrdctFields))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCountPrdctInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnShowPrdcts))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNamePrdctDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPrdctDelete))
                                .addGap(11, 11, 11)))
                        .addGap(35, 35, 35)
                        .addComponent(lblOutputProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnExit))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamePrdctInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamePrdctInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamePrdctInsertActionPerformed

    private void txtPricePrdctInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPricePrdctInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPricePrdctInsertActionPerformed

    private void btnPrdctInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrdctInsertActionPerformed

       setName(txtNamePrdctInsert.getText());
       setPrice(Double.parseDouble(txtPricePrdctInsert.getText()));
//       
//       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yy");
//       LocalDate date = LocalDate.parse(txtExpirationDatePrdctInsert.getText(), formatter);
//       setDateOfExpire(date);
       
       setCount(Integer.parseInt(txtCountPrdctInsert.getText()));
       try{
       Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/Stiliyan/Desktop/java/Net Beans/Magazin.accdb");
       Statement s = con.createStatement();
           String query = "INSERT INTO Продукт ([Име], [Цена], [Бройка] ) VALUES('" + getName() + "' , '" + getPrice() + "' , '"  + getCount() + "')";
           Statement st = con.createStatement();
           st.executeUpdate(query);
            lblOutputProducts.setText("Продукт добавен успешно!");
           con.close();
       }
       catch(SQLException ex){
       lblOutputProducts.setText("Неуспешно добавяне!");
       Logger.getLogger(PotrebitelFrame.class.getName()).log(Level.SEVERE,null,ex);
       }      
    }//GEN-LAST:event_btnPrdctInsertActionPerformed

    private void btnShowPrdctsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPrdctsActionPerformed
        StringBuilder sb = new StringBuilder();
        try{
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/Stiliyan/Desktop/java/Net Beans/Magazin.accdb");
           Statement s = con.createStatement();
           ResultSet rs = s.executeQuery("SELECT [Име], [Цена], [Бройка] FROM Продукт");
           while(rs.next()){
             sb.append(rs.getString(1)).append(" / ").append(rs.getString(2)).append("лв. / ").append(rs.getString(3)).append("бр.");
             sb.append(System.getProperty("line.separator"));
           }
           areaShowProducts.setText(sb.toString());
           con.close();
        }
        catch (SQLException ex) {
            lblOutputProducts.setText(String.format("Exception: %s", ex.getMessage()));
        }
    }//GEN-LAST:event_btnShowPrdctsActionPerformed

    private void btnClearPrdctFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPrdctFieldsActionPerformed
        txtNamePrdctInsert.setText("");
        txtPricePrdctInsert.setText("");
        txtCountPrdctInsert.setText("");
        txtNamePrdctDelete.setText("");
        areaShowProducts.setText("");
        lblOutputProducts.setText("");
    }//GEN-LAST:event_btnClearPrdctFieldsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrdctDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrdctDeleteActionPerformed
        try{
           Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/Stiliyan/Desktop/java/Net Beans/Magazin.accdb");
           
           PreparedStatement ps = con.prepareStatement("DELETE FROM Продукт WHERE Име = ?");
           String a = txtNamePrdctDelete.getText();
            ps.setString(1, a.toString());
            ps.executeUpdate();
            lblOutputProducts.setText("Продукт премахнат успешно!");
           con.close();
        }
        catch (SQLException ex) {
            lblOutputProducts.setText("Неуспешно премахване!");
            Logger.getLogger(PotrebitelFrame.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnPrdctDeleteActionPerformed

    private void txtNamePrdctDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamePrdctDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamePrdctDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaShowProducts;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearPrdctFields;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrdctDelete;
    private javax.swing.JButton btnPrdctInsert;
    private javax.swing.JButton btnShowPrdcts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOutputProducts;
    private javax.swing.JTextField txtCountPrdctInsert;
    private javax.swing.JTextField txtNamePrdctDelete;
    private javax.swing.JTextField txtNamePrdctInsert;
    private javax.swing.JTextField txtPricePrdctInsert;
    // End of variables declaration//GEN-END:variables
}
